### ISSUE TITLE
Error loading force with handleForceFromRaw

### ISSUE THREAD

**Issue by mattperich** [limblab/ClassyDataAnalysis#11]
The length of the raw_force and cds.enc data do not match in cds.handleForceFromRaw, throwing an error when it defines handleForce (e.g. line 56). It's related to the truncated data in forceFromNSx, perhaps because dual cerebus recordings do not have the need to truncate since they reset time when the second cerebus starts?

**Comment by raeedcho** [comment]
Was this solved?

**Comment by mattperich** [comment]
Yes. The bug came when there were timestamps for force that were outside of the timestamps for the encoder data. I committed some changes that keeps the force data on its own time scale (so length doesn't matter) until the times are trimmed with sanitizetimewindows.  I'm a github issue n00b though and didn't close this.
